/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();

  // you can add a icon to a html canvas. simply supply its element id and the weather you want to show.
  skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  skycons.add("day1", Skycons.CLEAR_DAY);
  skycons.add("day2", Skycons.CLOUDY);
  skycons.add("day3", Skycons.RAIN);

  // start all icons animation!
  skycons.play();

  // update a icon on  canvas by its id
  skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);

/*
Get value from Bootstrap dropdown menu
*/
var forecast;
var city = "Taipei";
var cities = ["Taipei", "New Taipei", "Taichung", "Tainan", "Kaohsiung", "Keelung", "Taoyuan", "Hsinchu", "Miaoli", "Changhua", "Nantou", "Yunlin","Chiayi", "Pingtung", "Yilan", "Hualien", "Taitung", "Penghu", "Kinmen"];
var change = false;
var weather;
var chooserIcon = function(code) {
    if ((code > 0 && code < 5) || code == 12 || (code == 35) || (code >= 37 && code < 41) || (code == 45 || code == 47)) {
        return Skycons.RAIN;
    } else if ((code > 4 && code <= 11) || (code == 18)) {
        return Skycons.SLEET;
    } else if ((code > 30 && code < 33) || (code == 36)) {
        return Skycons.CLEAR_DAY;
    } else if (code == 34) {
        return Skycons.CLEAR_NIGHT;
    } else if (code == 30 || code == 28 || code == 26 || code == 44) {
        return Skycons.PARTLY_CLOUDY_DAY;
    } else if (code == 27 || code == 29) {
        return Skycons.PARTLY_CLOUDY_NIGHT;
    } else if ((code > 12 && code < 18) || (code >= 41 && code < 44) || (code == 46)) {
        return Skycons.SNOW;
    } else if (code > 19 && code < 23) {
        return Skycons.FOG;
    } else if (code == 24) {
        return Skycons.WIND;
    }
}

var f2c = function(temp) {
    return Math.round((temp - 32) / (9 / 5));
}

function getJsonUntilSuccess (url , cb){
    $.getJSON (url , function (s){   
      if (s.query.results){
          cb(s);              
      }else {
          getJsonUntilSuccess(url,cb);
      }
    })
}

$(document).ready(function(){
    getData("Taipei");
    $(".dropdown-toggle").html("Taipei");
    $.each(cities, function(i, val) {
        src = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22" + val + "%20City%2C%20ak%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys"
        $(".dropdown-menu").append("<li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"#\"><p><span id='cityData'>" + val + "</span><span id = 'temp" + i + "' style='float:right'></span></p></a></li>")
        getJsonUntilSuccess(src, function(data){
          $("#temp" + i).text(f2c(data.query.results.channel.item.condition.temp)).append("&#8451;");
        })
    })
    $('#dropdown li').on('click', function(){
        var thisCity = $(this).find("#cityData").text();
        getData(thisCity);
        change = true;
        $(".temperature").text(thisCity);
        console.log(thisCity);
        $(".dropdown-toggle").html(thisCity);
    })
})

var getData = function(city){
  var apiUrl = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22" + city + "%20City%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys"
      getJsonUntilSuccess(apiUrl, function(s){
        console.log(s);
        forecast = new Array();
        for(var i = 0; i < 4; i++){
          forecast.push(s.query.results.channel.item.forecast[i]);
        }
        if(!change){
          $(".temperature").append(f2c(s.query.results.channel.item.condition.temp));
          $(".dropdown-toggle").append(f2c(s.query.results.channel.item.condition.temp));
        }
        $(".temperature").text(f2c(s.query.results.channel.item.condition.temp));
        var todayWeather = forecast[0].code;
        var day1Weather = forecast[1].code;
        var day2Weather = forecast[2].code;
        var day3Weather = forecast[3].code;
        if (chooserIcon(todayWeather) === Skycons.RAIN ){
          weather = "raining";
        }else if(chooserIcon(todayWeather) === Skycons.SLEET ){
          weather = "sleeting";
        }else if(chooserIcon(todayWeather) === Skycons.CLEAR_DAY ){
          weather = "clear day";
        }else if(chooserIcon(todayWeather) === Skycons.CLEAR_NIGHT ){
          weather = "clear night";
        }else if(chooserIcon(todayWeather) === Skycons.PARTLY_CLOUDY_DAY ){
          weather = "cloudy day";
        }else if(chooserIcon(todayWeather) === Skycons.PARTLY_CLOUDY_NIGHT ){
          weather = "cloudy night";
        }else if(chooserIcon(todayWeather) === Skycons.SNOW ){
          weather = "snow";
        }else if(chooserIcon(todayWeather) === Skycons.FOG ){
          weather = "foggy";
        }else if(chooserIcon(todayWeather) === Skycons.WIND ){
          weather = "windy";
        }
        $("#weather").text(weather);
        skycons.set("today", chooserIcon(todayWeather));
        skycons.set("day1", chooserIcon(day1Weather));
        skycons.set("day2", chooserIcon(day2Weather));
        skycons.set("day3", chooserIcon(day3Weather));

        var todayDate = forecast[0].date;
        var day1Date = forecast[1].date;
        var day2Date = forecast[2].date;
        var day3Date = forecast[3].date;
        $(".date").text(todayDate);
        $("#day1Date").text(day1Date);
        $("#day2Date").text(day2Date);
        $("#day3Date").text(day3Date);
        var temp1H = f2c(forecast[1].high);
        console.log(temp1H);
        console.log(forecast[0].high);
        var temp1L = f2c(forecast[1].low);
        var temp2H = f2c(forecast[2].high);
        var temp2L = f2c(forecast[2].low);
        var temp3H = f2c(forecast[3].high);
        var temp3L = f2c(forecast[3].low);
        $("#day1Tem").text(temp1L+" - "+temp1H);
        $("#day2Tem").text(temp2L+" - "+temp2H);
        $("#day3Tem").text(temp3L+" - "+temp3H);
    })
}